name: Test Build
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: test
        uses: puernya/tg-bot-upload@v1
        with:
          bot-id: ${{ secrets.BOT_ID }}
          chat-id: ${{ secrets.CHAT_ID }}
          topic-id: ${{ secrets.TOPIC_ID }}
          file-path: |
            *.txt
            */*.yml
          caption-path: release.txt
